import type { Metadata } from 'next'
import { Inter, Lusitana } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const lusitana: any = Lusitana({ subsets: ['latin'],
  weight: ['400', '700']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {children}
        <p
        className={`${lusitana.className} text-xl text-white-800 md:text-3xl md:leading-normal`}>
          <strong>Welcome The Depeche mode Corner of Life.</strong>
      </p>
      </body>
    </html>
  )
}
